### ISSUE TITLE
Great plugin! 

### ISSUE THREAD

**Issue by thecodingmike** [RedXi/vatsimbrief-helper#1]
Hi,

First of all great work! I like the plugin. Some feedback:

It would be nice to have different mappings where the files are sent to, not just 1 folder. For example; the FMC file my addon uses is in a different map. The PDF I would like to automaticly be put in the Avitab Charts folder and the Vpilot file in another dedicated Xpilot folder.

I was trying to assign keys to popup the different helper windows but I couldn't find the related plugin actions. Selecting the fly with lua menu and then the window is a bit time consuming ....

My 2 cents, I will certainly continue using it.

Grtz

**Comment by RedXi** [comment]
Hi edje,

thank you for the feedback! I definitely agree that both features are very valuable. I'm going to implement them rather soon.

Best regards

Red

**Comment by edje** [comment]
Hi Red,

Do you have Discord or something?

I’ve attached a screenshot from a program we use in real life during daily
operations. It produces a screen with all the PREFLIGHT INFO we need to
load the FMC. It is presented in a nice way. I think this would be nice to
add to your plugin also.

Kind regards, please keep this screenshot for yourself.

Mike



Op zo 11 okt. 2020 om 01:54 schreef RedXi <notifications@github.com>

**Comment by RedXi** [comment]
I just uploaded a new release supporting hot keys for window toggles.

@edje It seems it's not possible to have a private exchange here, but we can use the X-Plane forum: https://forums.x-plane.org/index.php?/profile/855315-redxiii/ Looking forward to hearing from you!

Best regards

Red

**Comment by RedXi** [comment]
Commands (for hotkeys) and flight plan specific destination folders have been released in v1.0.10
