### ISSUE TITLE
Install of vatsimbrief-helper crashed lua

### ISSUE THREAD

**Issue by mrice96680** [RedXi/vatsimbrief-helper#8]
Hi, I installed vatsimbrief-helper using the .exe installer.  Started X-Plane 11 and the windows came up.  I added my SimBrief username and all of the vatsimbrief-helper and VR Radio Helper windows went black.  No text.  Red text at top right of screen indicating Lua stopped.  I would uninstall and reinstall but not sure which folders and files to delete.  Also happy to send any log files to you if you let me know which ones to create or grab.

![vatsimbrief helper crash screenshot_2](https://user-images.githubusercontent.com/95989247/145697116-94dec427-deb6-4923-9e2c-5bd9aa769be7.PNG)
![vatsimbrief helper crash screenshot](https://user-images.githubusercontent.com/95989247/145697118-a973d4ee-2b5a-498f-befc-d40c33937dc4.PNG)
.

**Comment by RedXi** [comment]
Hi, thank you for reporting this. Could you attach the "Log.txt" file and optionally also "FlyWithLua_Debug.txt" (if present) in the X-Plane folder, so I can have a look at what's going on.

**Comment by mrice96680** [comment]
Appreciate you looking into it.  Attached are the two files.  Let me know what else you need.  If I should uninstall/delete the scripts and start fresh, any instructions on what to remove would be great
[Log.txt](https://github.com/RedXi/vatsimbrief-helper/files/7699499/Log.txt)
[FlyWithLua_Debug.txt](https://github.com/RedXi/vatsimbrief-helper/files/7699500/FlyWithLua_Debug.txt)
.

**Comment by RedXi** [comment]
The application expected an Airline ICAO and a Flight Number to be set in the flight plan. A fix is provided with Release 1.0.30. You might just want to run the installer again to overwrite the existing installation. I would appreciate if you can provide some feedback if the problem has solved. Best regards!

**Comment by mrice96680** [comment]
Thanks much, issue is resolved!  Excited to use it.  Related to the other logged issue about VATSIM being unavailable, should I ask my question in that issue thread?  Wondering whether any creative solutions have come up as I'd definitely like to leverage it.

Really appreciate your work on this and the great app.  Blown away by this community!

**Comment by RedXi** [comment]
I'm glad to hear it's working now and you like it :) Feel free to involve in the VATSIM topic in the other issue thread. Best regards!
